version: "3"
services:
  backend:
    build:
      context: bot
      dockerfile: Dockerfile
    security_opt: 
      - 'apparmor=unconfined'
    volumes:
      - ./:/bot
      - ./node-persist-data:/bot/node-persist-data
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: local #local or prod
      TZ: "America/Denver"
    expose:
      - 8080
    restart: 'always'